//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrasnovExam2022.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopEnitites : DbContext
    {
        public ShopEnitites()
            : base("name=ShopEnitites")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auths> Auths { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Phones> Phones { get; set; }
        public virtual DbSet<Repares> Repares { get; set; }
        public virtual DbSet<RepareSklads> RepareSklads { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Material> Type_Material { get; set; }
        public virtual DbSet<Type_Pepares> Type_Pepares { get; set; }
        public virtual DbSet<Type_Phones> Type_Phones { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
