//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrasnovExam2022.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repares
    {
        public int Id_Repare { get; set; }
        public int Id_User { get; set; }
        public int Id_Phone { get; set; }
        public int Id_TypeRepare { get; set; }
    
        public virtual Phones Phones { get; set; }
        public virtual Type_Pepares Type_Pepares { get; set; }
        public virtual Users Users { get; set; }
    }
}
