//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrasnovExam2022.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Pepares
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Type_Pepares()
        {
            this.Repares = new HashSet<Repares>();
        }
    
        public int Id_TypeRepare { get; set; }
        public string Name_Repare { get; set; }
        public Nullable<int> Id_TypeMaterial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repares> Repares { get; set; }
        public virtual Type_Material Type_Material { get; set; }
    }
}
